### ISSUE TITLE
大佬！能不能出个视频教程啊？小白不会啊

### ISSUE THREAD

**Issue by AbelCccn** [ProudMuBai/GoFilm#35]

**Comment by ProudMuBai** [comment]
过两天我看看写个详细点的文档吧，最近有点忙，后面有时间了试着写下shell脚本去执行一下试试

**Comment by 196180** [comment]
==1.warp获取==

wget -N https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh && bash menu.sh

==2.docker安装==

apt update -y && apt install -y curl wget sudo && apt install -y docker && apt install -y docker-compose && apt install -y unzip

==3.安装方法:创建一个 docker-compose.yml 文件==

cd /root

```
mkdir npm && cd /root/npm && touch docker-compose.yml
```

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

```
docker-compose up -d
```

==4.在opt下拉取github文本==

cd /opt

git clone https://github.com/ProudMuBai/GoFilm.git

==5.将/opt/GoFilm/film移动film文件到/opt==

cd /opt/GoFilm/film

mv /opt/GoFilm/film /opt

==6.在film文件中建立镜像==

cd /opt/film

将docker文件端口改为3600:80

docker-compose build    ==版本改为3==

==7.运行镜像==

docker-compose up -d
