### ISSUE TITLE
老电视盒子armv7l架构没有docker版本的mysql的解决方案

### ISSUE THREAD

**Issue by Andrew8102** [ProudMuBai/GoFilm#70]
可以使用[One more Docker MySQL project for ARM devices](https://github.com/biarms/mysql)项目，只需要在`docker-compose.yml`文件的mysql部分中修改为`biarms/mysql`的包就可以安装，我这边安装5.7版本的，可以参考https://github.com/biarms/mysql  项目自行选择构建好的armv7版本
```yml
mysql:
    container_name: film_mysql
    image: biarms/mysql:5.7
    privileged: true 
    ports:
    - 3610:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FilmSite
    networks:
      - film-network
    command: [
          'mysqld',
          '--default-authentication-plugin=mysql_native_password',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
```
